python benchmarks/benchmark_serving.py \
    --backend vllm \
    --model Qwen/Qwen-7B-Chat \
    --tokenizer Qwen/Qwen-7B-Chat \
    --trust-remote-code \
    --dataset benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json \
    --request-rate 10 \
    --num-prompts 1000 \
    --save-result \
    --exp-dir result \
    --exp-name kv-cache \
    --version 8 \